frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile*'
          - 'docker-compose*.yml'

enhancement:
  - title: '^feat(\([\w-]+\))?!?:'

bug:
  - title: '^fix(\([\w-]+\))?!?:'

refactor:
  - title: '^refactor(\([\w-]+\))?!?:'

style:
  - title: '^style(\([\w-]+\))?!?:'

performance:
  - title: '^perf(\([\w-]+\))?!?:'

test:
  - title: '^test(\([\w-]+\))?!?:'

chore:
  - title: '^chore(\([\w-]+\))?!?:'

build:
  - title: '^build(\([\w-]+\))?!?:'

breaking:
  - title: '^(\w+)(\([\w-]+\))?!:'
